/** Short labels belong on miniatures; full event names stay in the story panel. */
const labels: Record<string, string> = {
  'AI STRATEGY': 'AI 전략',
  'AI PLAN': '행동계획',
  'AI + LEARNING': 'AI 교육',
  TASK: '과제',
  MODEL: '모델',
  EVAL: '평가',
  IDEA: '제안',
  VOICE: '의견',
  ASK: '질문',
  DISCUSS: '토론',
  SHARE: '공유',
  NAVER: '네이버',
  UPSTAGE: '업스테이지',
  PRIMARY: '주 시스템',
  RECOVERY: '복구',
  KOREA: '한국',
  RIGHTS: '권리',
  COPYRIGHT: '저작권',
  CONTENT: '콘텐츠',
  DIALOGUE: '대화',
  'DEFENSE\nDATA': '국방\n데이터',
  'CIVIL AI': '민간 AI',
  TEST: '실증',
  'PUBLIC\nFORUM': '공론장',
  PLAN: '계획',
  STRUCTURED: '구조화',
  'YEAR ONE': '첫 1년',
  OPEN: '개방',
  REVIEW: '검토',
  RESTRICTED: '보호',
  ACCESS: '접근',
  SKILLS: '역량',
  WORK: '일자리',
  EDUCATION: '교육',
  DEMOCRACY: '민주주의',
  'EDU TF': '교육 TF',
  'SECURITY TF': '안보 TF',
  'REGION TF': '지역 TF',
  TRAIN: '학습',
  EVALUATE: '평가',
  LEARN: '개선',
  MEMORY: '메모리',
  AGENTS: '에이전트',
  COMPUTE: '연산',
  'K-MOONSHOT': 'K-문샷',
};
export const stageText = (text: string) => labels[text] ?? text;
